In [1]:
import numpy as np

# Numpy array

In [2]:
liste=[20,30,40]

In [4]:
np.array(liste)

array([20, 30, 40])

In [5]:
matrixlistesi=[[10,20,30],[40,50,60],[70,80,90]]

In [6]:
np.array(matrixlistesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# arrange

In [7]:
range(0,10)

range(0, 10)

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

# zeros 

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace
verilen aralıkta istenilen sayı kadar eşit aralıklı küme oluşturur.

In [23]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [24]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

# eye

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random 

In [27]:
np.random.randn(8)

array([-0.24135744,  0.65193439, -1.34625241, -1.135638  ,  0.61804656,
       -1.36923299, -0.26855718,  0.63601099])

In [28]:
np.random.randn(4)

array([-0.2017319 ,  0.78753712, -1.4262308 ,  1.72541329])

In [29]:
np.random.randn(4,4)

array([[ 0.57057455,  0.902393  , -0.47578488,  1.07428993],
       [-1.28572721, -1.127369  ,  0.80018475,  0.05270907],
       [-0.79051536,  0.24893922, -0.61555106, -0.29105363],
       [-0.05738437, -2.19234103,  0.2401823 ,  1.15756189]])

In [30]:
np.random.randint(1,10)

6

In [31]:
np.random.randint(1,300,5)

array([192, 158,  52,  31, 194])

In [32]:
benimnumpydizim=np.arange(30)

In [33]:
benimnumpydizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
benimrandomdizim=np.random.randint(0,100,30)

In [35]:
benimrandomdizim

array([28, 29, 34,  8,  7, 44, 28, 73, 81, 86, 28, 86, 73, 90, 46, 46, 34,
       87, 61, 78, 33, 95, 83, 51, 65, 23, 20, 49, 22, 25])

# numpy dizi methodları

In [36]:
benimnumpydizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
benimnumpydizim.max()

29

In [39]:
benimnumpydizim.min()

0

In [40]:
benimrandomdizim.max()

95

In [41]:
benimrandomdizim.min()

7

In [43]:
benimrandomdizim.argmax()

21

In [44]:
benimrandomdizim.argmin()

4

In [45]:
benimnumpydizim.shape

(30,)

In [46]:
benimnumpydizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
reshapedizim=benimnumpydizim.reshape(5,6)

In [48]:
reshapedizim.shape

(5, 6)

# Numpy indexler 

In [52]:
benimdizim=np.arange(0,5)

In [55]:
benimdizim=np.arange(0,15)

In [56]:
benimdizim[5]

5

In [57]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
benimdizim[3:8]

array([3, 4, 5, 6, 7])

In [59]:
benimdizim[3:8]= -5

In [60]:
benimdizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [61]:
baskadizi=np.arange(0,24)

In [62]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [76]:
slicingdizisi=baskadizi[4:9]

In [77]:
slicingdizisi

array([4, 5, 6, 7, 8])

In [78]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [79]:
slicingdizisi

array([4, 5, 6, 7, 8])

In [80]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [81]:
slicingdizisi[:]

array([4, 5, 6, 7, 8])

In [82]:
type(slicingdizisi)

numpy.ndarray

In [84]:
slicingdizisi[:]=700

In [85]:
slicingdizisi

array([700, 700, 700, 700, 700])

In [86]:
baskadizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [88]:
ornekdizi=np.arange(0,24)

In [89]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [92]:
ornekdizikopyası=ornekdizi.copy()

In [93]:
ornekdizikopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [94]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [95]:
ornekdizikopyaslicing=ornekdizikopyası[3:6]

In [98]:
ornekdizikopyaslicing[:]=800

In [99]:
ornekdizikopyaslicing

array([800, 800, 800])

In [100]:
ornekdizikopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [101]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matriks İndexler

In [103]:
benimlistem=[[10,20,30],[20,30,40],[40,50,60]]

In [104]:
benimmatrixdizim=np.array(benimlistem)

In [105]:
benimmatrixdizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [106]:
benimmatrixdizim[0]

array([10, 20, 30])

In [107]:
benimmatrixdizim[1][2]

40

In [108]:
benimmatrixdizim[1,2]

40

In [109]:
benimmatrixdizim[1:,2]

array([40, 60])

In [110]:
yeniliste=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [111]:
yenimatrix=np.array(yeniliste)

In [112]:
yenimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
yenimatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

# Numpy Operasyonlar

In [115]:
yenibirdizi=np.arange(5,25)

In [116]:
yenibirdizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [118]:
yenibirdizi=np.random.randint(1,100,20)

In [119]:
yenibirdizi

array([79,  8, 60, 23, 48, 45, 52, 98, 59, 18,  9, 62,  3, 50, 29, 14, 30,
       31, 53,  2])

In [121]:
yenibirdizi>24

array([ True, False,  True, False,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True, False,  True,  True,
        True, False])

In [122]:
yenibirdizi

array([79,  8, 60, 23, 48, 45, 52, 98, 59, 18,  9, 62,  3, 50, 29, 14, 30,
       31, 53,  2])

In [123]:
sonucdizisi=yenibirdizi>24

In [125]:
sonucdizisi

array([ True, False,  True, False,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True, False,  True,  True,
        True, False])

In [126]:
yenibirdizi[sonucdizisi]

array([79, 60, 48, 45, 52, 98, 59, 62, 50, 29, 30, 31, 53])

In [127]:
yenibirdizi[yenibirdizi>24]

array([79, 60, 48, 45, 52, 98, 59, 62, 50, 29, 30, 31, 53])

In [128]:
sondizi=np.arange(0,24)

In [129]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [130]:
sondizi+sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [131]:
sondizi*sondizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [132]:
sondizi-sondizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [133]:
sondizi/sondizi

C:\Users\Admin\AppData\Local\Temp/ipykernel_164076/2654503216.py:1: RuntimeWarning: invalid value encountered in true_divide
  sondizi/sondizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [134]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [135]:
np.max(sondizi)

23

In [137]:
np.min(sondizi)

0